environment:
  matrix:
    - BUILDER: VisualC
      CPU:     x86
    - BUILDER: VisualC
      CPU:     x64
#   - BUILDER: clang
#     CPU:     x86
#   - BUILDER: clang
#     CPU:     x64
    - BUILDER: MinGW
      CPU:     x86
#   - BUILDER: MinGW
#     CPU:     x64
    - BUILDER: djgpp
      CPU:     x86

matrix:
  #
  # Immediately finish build if one of the above jobs fails.
  #
  fast_finish: true

install:
  #
  # Set the PATH for 'make' + 'sh' used by 'MinGW', 'djgpp', 'CygWin' etc.
  #
  - cmd: set PATH=%PATH%;c:\msys64\usr\bin

  #
  # Set compiler environment for MSVC/clang-cl first.
  #
  - cmd: if %BUILDER%. == VisualC.         call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %CPU%
  - cmd: if %BUILDER%. == clang.           call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %CPU%
  - cmd: if %BUILDER%-%CPU%. == MinGW-x86. set PATH=c:\msys64\MinGW32\bin;%PATH%
  - cmd: if %BUILDER%-%CPU%. == MinGW-x64. set PATH=c:\msys64\MinGW64\bin;%PATH%
  - cmd: if %BUILDER%-%CPU%. == MinGW      set PATH=c:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\bin;%PATH%

build_script:
    - cmd: appveyor-script.bat build_src
    - cmd: appveyor-script.bat build_bin

test_script:
    - cmd: appveyor-script.bat test

