environment:
  matrix:
    - BUILDER: VisualC
      CPU:     x86
    - BUILDER: VisualC
      CPU:     x64
#   - BUILDER: clang
#     CPU:     x86
    - BUILDER: clang
      CPU:     x64
#   - BUILDER: MinGW
#     CPU:     x86
#   - BUILDER: MinGW
#     CPU:     x64
    - BUILDER: djgpp
      CPU:     x86

build_script:
    - cmd: appveyor-script.bat build

#
# To-do
#
# test_script:
#    - cmd: appveyor-script.bat test

